### PR TITLE
check python if AUTOSWITCH_DEFAULT_PYTHON is set

### LINKED ISSUE #182: python binary not found on PATH, zsh-autoswitch-virtualenv plugin will be disabled
# Issue Details

Plugin won't load with error **WARNING: python binary not found on PATH.**

I have python 3.10.x installed on as package and as macOS Monterey might not have default python 2.x installed. This causes the check 
```zsh
$ type python 
python not found
```
although I have properly installed python3
```zsh
$ type python3
python3 is /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
```

I have set 
```
export AUTOSWITCH_DEFAULT_PYTHON=python3
```
in my ~/.zshrc before loading the oh-my-zsh/plugin, however this has no effect as the `python` string is hardcoded at https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv/blob/master/autoswitch_virtualenv.plugin.zsh#L416

## Operating System (uname -a)
Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

## zsh version (zsh --version)
zsh 5.8.1 (x86_64-apple-darwin21.0)

## autoswitch-virtualenv version

```
echo "$AUTOSWITCH_VERSION"
3.6.0
```

## How is zsh-autoswitch-virtualenv installed?

- oh-my-zsh

## Steps to reproduce the issue
most probably easiest way to reproduce is remove `python` symlink pointing to either `python2` or `python3`

### PR DESCRIPTION
**Pull request by adamko147**
Fixes #182

### CODE REVIEW

**Review by MichaelAquilina — APPROVED** [review]
Looks good :) I'll be running this locally for a bit before merging.

Thanks for the PR!

**Comment by adamko147** [comment]
> I think the CircleCI failure is unrelated and possibly due to an incident within circleci itself. I'll trigger a rebuild at a later stage.

Thanks, when I try to trigger CircleCI on my repo, I got an error
https://app.circleci.com/pipelines/github/adamko147/zsh-autoswitch-virtualenv/1/workflows/6789aad5-6563-40ee-bc20-1138d960d7e9/jobs/2?invite=true#step-105-203 saying
```
✘ correct version exported
'3.6.0' is not the same as ''
```
which I think is also not much related to the change I did.

**Comment by cunha** [comment]
I just ran into this issue; and it's nice that we have a solution. Just bumping to +1 the merge.

**Comment by MichaelAquilina** [comment]
@adamko147 could you try rebasing your PR on latest main to see if the circleci issue is resolved? I tried re-opening the PR to see if it would trigger again but that did not work

**Comment by adamko147** [comment]
@MichaelAquilina any idea how to re-trigger the CircleCI on the PR? Thanks!

**Comment by fnicastri** [comment]
@MichaelAquilina 
Will you merge this?

**Review by MichaelAquilina — APPROVED** [review]

**Comment by MichaelAquilina** [comment]
Thank you for the change and sorry for the delay :)

**Pull request merged**
